# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KMUP <- function(X, b, d, xx, e, L, Ve, pi) {
    .Call('_bWGR_KMUP', PACKAGE = 'bWGR', X, b, d, xx, e, L, Ve, pi)
}

KMUP2 <- function(X, Use, b, d, xx, E, L, Ve, pi) {
    .Call('_bWGR_KMUP2', PACKAGE = 'bWGR', X, Use, b, d, xx, E, L, Ve, pi)
}

emBA <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emBA', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBB <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBB', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emBC <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBC', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emDE <- function(y, gen, R2 = 0.5) {
    .Call('_bWGR_emDE', PACKAGE = 'bWGR', y, gen, R2)
}

emRR <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emRR', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBL <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emBL', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emEN <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emEN', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emML <- function(y, gen, D = NULL) {
    .Call('_bWGR_emML', PACKAGE = 'bWGR', y, gen, D)
}

emGWA <- function(y, gen) {
    .Call('_bWGR_emGWA', PACKAGE = 'bWGR', y, gen)
}

BayesA <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesB <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesC <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesC', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesL <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesL', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesRR <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesCpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesCpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesDpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesDpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesA2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

BayesB2 <- function(y, X1, X2, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB2', PACKAGE = 'bWGR', y, X1, X2, it, bi, pi, df, R2)
}

BayesRR2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

emML2 <- function(y, X1, X2, D1 = NULL, D2 = NULL) {
    .Call('_bWGR_emML2', PACKAGE = 'bWGR', y, X1, X2, D1, D2)
}

CNT <- function(X) {
    .Call('_bWGR_CNT', PACKAGE = 'bWGR', X)
}

IMP <- function(X) {
    .Call('_bWGR_IMP', PACKAGE = 'bWGR', X)
}

GAU <- function(X) {
    .Call('_bWGR_GAU', PACKAGE = 'bWGR', X)
}

GRM <- function(X, Code012 = FALSE) {
    .Call('_bWGR_GRM', PACKAGE = 'bWGR', X, Code012)
}

SPC <- function(y, blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPC', PACKAGE = 'bWGR', y, blk, row, col, rN, cN)
}

SPM <- function(blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPM', PACKAGE = 'bWGR', blk, row, col, rN, cN)
}

mtgsru <- function(Y, X, b, vb, ve, iG, maxit = 50L) {
    .Call('_bWGR_mtgsru', PACKAGE = 'bWGR', Y, X, b, vb, ve, iG, maxit)
}

lasso <- function(y, gen) {
    .Call('_bWGR_lasso', PACKAGE = 'bWGR', y, gen)
}

emBCpi <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBCpi', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

NNSEARCH <- function(blk, row, col, rN, cN) {
    .Call('_bWGR_NNSEARCH', PACKAGE = 'bWGR', blk, row, col, rN, cN)
}

GSFLM <- function(y, e, gen, b, Lmb, xx, cxx, maxit = 50L) {
    .Call('_bWGR_GSFLM', PACKAGE = 'bWGR', y, e, gen, b, Lmb, xx, cxx, maxit)
}

GSRR <- function(y, e, gen, b, Lmb, xx, cxx, maxit = 50L) {
    .Call('_bWGR_GSRR', PACKAGE = 'bWGR', y, e, gen, b, Lmb, xx, cxx, maxit)
}

EigenARC <- function(X, centralizeX = TRUE, cores = 1L) {
    .Call('_bWGR_EigenARC', PACKAGE = 'bWGR', X, centralizeX, cores)
}

EigenGAU <- function(X, phi = 1.0, cores = 1L) {
    .Call('_bWGR_EigenGAU', PACKAGE = 'bWGR', X, phi, cores)
}

EigenGRM <- function(X, centralizeZ = TRUE, cores = 1L) {
    .Call('_bWGR_EigenGRM', PACKAGE = 'bWGR', X, centralizeZ, cores)
}

EigenCNT <- function(X, cores = 1L) {
    .Call('_bWGR_EigenCNT', PACKAGE = 'bWGR', X, cores)
}

EigenEVD <- function(A, cores = 1L) {
    .Call('_bWGR_EigenEVD', PACKAGE = 'bWGR', A, cores)
}

EigenBDCSVD <- function(X, cores = 1L) {
    .Call('_bWGR_EigenBDCSVD', PACKAGE = 'bWGR', X, cores)
}

EigenJacobiSVD <- function(X, cores = 1L) {
    .Call('_bWGR_EigenJacobiSVD', PACKAGE = 'bWGR', X, cores)
}

EigenAcc <- function(X1, X2, h2 = 0.5, cores = 1L) {
    .Call('_bWGR_EigenAcc', PACKAGE = 'bWGR', X1, X2, h2, cores)
}

GS2EIGEN <- function(e, X, b, XX, Lmb) {
    .Call('_bWGR_GS2EIGEN', PACKAGE = 'bWGR', e, X, b, XX, Lmb)
}

mrr2X <- function(Y, X1, X2) {
    .Call('_bWGR_mrr2X', PACKAGE = 'bWGR', Y, X1, X2)
}

MRR3 <- function(Y, X, maxit = 500L, tol = 10e-9, cores = 1L, TH = FALSE, NLfactor = 0.0, InnerGS = FALSE, NoInv = FALSE, HCS = FALSE, XFA = FALSE, ACS = FALSE, NumXFA = 3L, R2 = 0.5, gc0 = 0.5, df0 = 1.0, updateMu = FALSE, weight_prior_h2 = 0.01, weight_prior_gc = 0.01, PenCor = 0.0, MinCor = 1.0, uncorH2below = 0.0, roundGCupFrom = 1.0, roundGCupTo = 1.0, roundGCdownFrom = 1.0, roundGCdownTo = 0.0, bucketGCfrom = 1.0, bucketGCto = 1.0, DeflateMax = 0.9, DeflateBy = 0.0, OneVarB = FALSE, OneVarE = FALSE, verbose = FALSE) {
    .Call('_bWGR_MRR3', PACKAGE = 'bWGR', Y, X, maxit, tol, cores, TH, NLfactor, InnerGS, NoInv, HCS, XFA, ACS, NumXFA, R2, gc0, df0, updateMu, weight_prior_h2, weight_prior_gc, PenCor, MinCor, uncorH2below, roundGCupFrom, roundGCupTo, roundGCdownFrom, roundGCdownTo, bucketGCfrom, bucketGCto, DeflateMax, DeflateBy, OneVarB, OneVarE, verbose)
}

MRR3F <- function(Y, X, maxit = 500L, tol = 10e-9, cores = 1L, TH = FALSE, NonLinearFactor = 0.0, InnerGS = FALSE, NoInv = FALSE, HCS = FALSE, XFA = FALSE, ACS = FALSE, NumXFA = 3L, R2 = 0.5, gc0 = 0.5, df0 = 1.0, updateMu = FALSE, weight_prior_h2 = 0.01, weight_prior_gc = 0.01, PenCor = 0.0, MinCor = 1.0, uncorH2below = 0.0, roundGCupFrom = 1.0, roundGCupTo = 1.0, roundGCdownFrom = 1.0, roundGCdownTo = 0.0, bucketGCfrom = 1.0, bucketGCto = 1.0, DeflateMax = 0.9, DeflateBy = 0.0, OneVarB = FALSE, OneVarE = FALSE, verbose = FALSE) {
    .Call('_bWGR_MRR3F', PACKAGE = 'bWGR', Y, X, maxit, tol, cores, TH, NonLinearFactor, InnerGS, NoInv, HCS, XFA, ACS, NumXFA, R2, gc0, df0, updateMu, weight_prior_h2, weight_prior_gc, PenCor, MinCor, uncorH2below, roundGCupFrom, roundGCupTo, roundGCdownFrom, roundGCdownTo, bucketGCfrom, bucketGCto, DeflateMax, DeflateBy, OneVarB, OneVarE, verbose)
}

mrr_svd <- function(Y, W) {
    .Call('_bWGR_mrr_svd', PACKAGE = 'bWGR', Y, W)
}

MLM <- function(Y, X, Z, maxit = 500L, logtol = -8, cores = 1L, verb = FALSE, df0 = 1.1) {
    .Call('_bWGR_MLM', PACKAGE = 'bWGR', Y, X, Z, maxit, logtol, cores, verb, df0)
}

solver1x <- function(Y, X, maxit = 100L, tol = 10e-7, df0 = 20.0) {
    .Call('_bWGR_solver1x', PACKAGE = 'bWGR', Y, X, maxit, tol, df0)
}

solver2x <- function(Y, X1, X2, maxit = 100L, tol = 10e-7, df0 = 20.0) {
    .Call('_bWGR_solver2x', PACKAGE = 'bWGR', Y, X1, X2, maxit, tol, df0)
}

UVBETA <- function(Y, X) {
    .Call('_bWGR_UVBETA', PACKAGE = 'bWGR', Y, X)
}

MEGA <- function(Y, X, npc = -1L) {
    .Call('_bWGR_MEGA', PACKAGE = 'bWGR', Y, X, npc)
}

GSEM <- function(Y, X, npc = -1L) {
    .Call('_bWGR_GSEM', PACKAGE = 'bWGR', Y, X, npc)
}

solver1xF <- function(Y, X, maxit = 100L, tol = 10e-7, df0 = 20.0) {
    .Call('_bWGR_solver1xF', PACKAGE = 'bWGR', Y, X, maxit, tol, df0)
}

solver2xF <- function(Y, X1, X2, maxit = 100L, tol = 10e-7, df0 = 20.0) {
    .Call('_bWGR_solver2xF', PACKAGE = 'bWGR', Y, X1, X2, maxit, tol, df0)
}

FUVBETA <- function(Y, X) {
    .Call('_bWGR_FUVBETA', PACKAGE = 'bWGR', Y, X)
}

XFUVBETA <- function(Y, X) {
    .Call('_bWGR_XFUVBETA', PACKAGE = 'bWGR', Y, X)
}

XSEMF <- function(Y, X, npc = 0L) {
    .Call('_bWGR_XSEMF', PACKAGE = 'bWGR', Y, X, npc)
}

ZFUVBETA <- function(Y, X) {
    .Call('_bWGR_ZFUVBETA', PACKAGE = 'bWGR', Y, X)
}

ZSEMF <- function(Y, X, npc = 0L) {
    .Call('_bWGR_ZSEMF', PACKAGE = 'bWGR', Y, X, npc)
}

YSEMF <- function(Y, X, npc = -1L) {
    .Call('_bWGR_YSEMF', PACKAGE = 'bWGR', Y, X, npc)
}

EigenArcZ <- function(Zfndr, Zsamp, cores = 1L) {
    .Call('_bWGR_EigenArcZ', PACKAGE = 'bWGR', Zfndr, Zsamp, cores)
}

EigenGauZ <- function(Zfndr, Zsamp, phi = 1.0, cores = 1L) {
    .Call('_bWGR_EigenGauZ', PACKAGE = 'bWGR', Zfndr, Zsamp, phi, cores)
}

K2X <- function(K, MinEV = 1e-8, cores = 1L) {
    .Call('_bWGR_K2X', PACKAGE = 'bWGR', K, MinEV, cores)
}

MvSimY <- function(Ufndr, Zfndr, Zsamp, GxY, GxL, H2plot, nLoc = 20L, Seed = 123L) {
    .Call('_bWGR_MvSimY', PACKAGE = 'bWGR', Ufndr, Zfndr, Zsamp, GxY, GxL, H2plot, nLoc, Seed)
}

PEGS <- function(Y, X, maxit = 100L, logtol = -4.0, NonNegativeCorr = FALSE) {
    .Call('_bWGR_PEGS', PACKAGE = 'bWGR', Y, X, maxit, logtol, NonNegativeCorr)
}

ClusterBlup <- function(Y, X, lambda = 2.0) {
    .Call('_bWGR_ClusterBlup', PACKAGE = 'bWGR', Y, X, lambda)
}

IncMatrix <- function(x) {
    .Call('_bWGR_IncMatrix', PACKAGE = 'bWGR', x)
}

EM_recluster <- function(Y, C, rounds = 3L) {
    .Call('_bWGR_EM_recluster', PACKAGE = 'bWGR', Y, C, rounds)
}

Get_Cluster_Corr <- function(Y, C) {
    .Call('_bWGR_Get_Cluster_Corr', PACKAGE = 'bWGR', Y, C)
}

