# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EigenArcZ <- function(Zfndr, Zsamp, cores = 2L) {
    .Call('_bWGR_EigenArcZ', PACKAGE = 'bWGR', Zfndr, Zsamp, cores)
}

EigenGauZ <- function(Zfndr, Zsamp, phi = 1.0, cores = 2L) {
    .Call('_bWGR_EigenGauZ', PACKAGE = 'bWGR', Zfndr, Zsamp, phi, cores)
}

K2X <- function(K) {
    .Call('_bWGR_K2X', PACKAGE = 'bWGR', K)
}

MvSimY <- function(Ufndr, Zfndr, Zsamp, GxY, GxL, H2plot, nLoc = 20L, Seed = 123L) {
    .Call('_bWGR_MvSimY', PACKAGE = 'bWGR', Ufndr, Zfndr, Zsamp, GxY, GxL, H2plot, nLoc, Seed)
}

MLM <- function(Y, X, Z, maxit = 500L, logtol = -8, cores = 1L) {
    .Call('_bWGR_MLM', PACKAGE = 'bWGR', Y, X, Z, maxit, logtol, cores)
}

EigenARC <- function(X, centralizeX = TRUE, cores = 2L) {
    .Call('_bWGR_EigenARC', PACKAGE = 'bWGR', X, centralizeX, cores)
}

EigenGAU <- function(X, phi = 1.0, cores = 2L) {
    .Call('_bWGR_EigenGAU', PACKAGE = 'bWGR', X, phi, cores)
}

EigenGRM <- function(X, centralizeZ = TRUE, cores = 2L) {
    .Call('_bWGR_EigenGRM', PACKAGE = 'bWGR', X, centralizeZ, cores)
}

EigenCNT <- function(X, cores = 2L) {
    .Call('_bWGR_EigenCNT', PACKAGE = 'bWGR', X, cores)
}

EigenEVD <- function(A, cores = 2L) {
    .Call('_bWGR_EigenEVD', PACKAGE = 'bWGR', A, cores)
}

EigenBDCSVD <- function(X, cores = 2L) {
    .Call('_bWGR_EigenBDCSVD', PACKAGE = 'bWGR', X, cores)
}

EigenJacobiSVD <- function(X, cores = 2L) {
    .Call('_bWGR_EigenJacobiSVD', PACKAGE = 'bWGR', X, cores)
}

EigenAcc <- function(X1, X2, h2 = 0.5, cores = 2L) {
    .Call('_bWGR_EigenAcc', PACKAGE = 'bWGR', X1, X2, h2, cores)
}

GS2EIGEN <- function(e, X, b, XX, Lmb) {
    .Call('_bWGR_GS2EIGEN', PACKAGE = 'bWGR', e, X, b, XX, Lmb)
}

NNSEARCH <- function(blk, row, col, rN, cN) {
    .Call('_bWGR_NNSEARCH', PACKAGE = 'bWGR', blk, row, col, rN, cN)
}

GSFLM <- function(y, e, gen, b, Lmb, xx, cxx, maxit = 50L) {
    .Call('_bWGR_GSFLM', PACKAGE = 'bWGR', y, e, gen, b, Lmb, xx, cxx, maxit)
}

GSRR <- function(y, e, gen, b, Lmb, xx, cxx, maxit = 50L) {
    .Call('_bWGR_GSRR', PACKAGE = 'bWGR', y, e, gen, b, Lmb, xx, cxx, maxit)
}

mrr <- function(Y, X) {
    .Call('_bWGR_mrr', PACKAGE = 'bWGR', Y, X)
}

mrr2X <- function(Y, X1, X2) {
    .Call('_bWGR_mrr2X', PACKAGE = 'bWGR', Y, X1, X2)
}

MRR3 <- function(Y, X, maxit = 1000L, tol = 10e-9, cores = 2L, TH = FALSE, NLfactor = 0.0, HCS = FALSE, XFA2 = FALSE, R2 = 0.5, gc0 = 0.0, df0 = 0.0, PenCor = 0.0, MinCor = 1.0, InnerGS = FALSE, NoInv = FALSE) {
    .Call('_bWGR_MRR3', PACKAGE = 'bWGR', Y, X, maxit, tol, cores, TH, NLfactor, HCS, XFA2, R2, gc0, df0, PenCor, MinCor, InnerGS, NoInv)
}

KMUP <- function(X, b, d, xx, e, L, Ve, pi) {
    .Call('_bWGR_KMUP', PACKAGE = 'bWGR', X, b, d, xx, e, L, Ve, pi)
}

KMUP2 <- function(X, Use, b, d, xx, E, L, Ve, pi) {
    .Call('_bWGR_KMUP2', PACKAGE = 'bWGR', X, Use, b, d, xx, E, L, Ve, pi)
}

emBA <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emBA', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBB <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBB', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emBC <- function(y, gen, df = 10, R2 = 0.5, Pi = 0.75) {
    .Call('_bWGR_emBC', PACKAGE = 'bWGR', y, gen, df, R2, Pi)
}

emDE <- function(y, gen, R2 = 0.5) {
    .Call('_bWGR_emDE', PACKAGE = 'bWGR', y, gen, R2)
}

emRR <- function(y, gen, df = 10, R2 = 0.5) {
    .Call('_bWGR_emRR', PACKAGE = 'bWGR', y, gen, df, R2)
}

emBL <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emBL', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emEN <- function(y, gen, R2 = 0.5, alpha = 0.02) {
    .Call('_bWGR_emEN', PACKAGE = 'bWGR', y, gen, R2, alpha)
}

emML <- function(y, gen, D = NULL) {
    .Call('_bWGR_emML', PACKAGE = 'bWGR', y, gen, D)
}

emGWA <- function(y, gen) {
    .Call('_bWGR_emGWA', PACKAGE = 'bWGR', y, gen)
}

BayesA <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesB <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesC <- function(y, X, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesC', PACKAGE = 'bWGR', y, X, it, bi, pi, df, R2)
}

BayesL <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesL', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesRR <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesCpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesCpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesDpi <- function(y, X, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesDpi', PACKAGE = 'bWGR', y, X, it, bi, df, R2)
}

BayesA2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesA2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

BayesB2 <- function(y, X1, X2, it = 1500, bi = 500, pi = 0.95, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesB2', PACKAGE = 'bWGR', y, X1, X2, it, bi, pi, df, R2)
}

BayesRR2 <- function(y, X1, X2, it = 1500, bi = 500, df = 5, R2 = 0.5) {
    .Call('_bWGR_BayesRR2', PACKAGE = 'bWGR', y, X1, X2, it, bi, df, R2)
}

emML2 <- function(y, X1, X2, D1 = NULL, D2 = NULL) {
    .Call('_bWGR_emML2', PACKAGE = 'bWGR', y, X1, X2, D1, D2)
}

CNT <- function(X) {
    .Call('_bWGR_CNT', PACKAGE = 'bWGR', X)
}

IMP <- function(X) {
    .Call('_bWGR_IMP', PACKAGE = 'bWGR', X)
}

GAU <- function(X) {
    .Call('_bWGR_GAU', PACKAGE = 'bWGR', X)
}

GRM <- function(X, Code012 = FALSE) {
    .Call('_bWGR_GRM', PACKAGE = 'bWGR', X, Code012)
}

SPC <- function(y, blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPC', PACKAGE = 'bWGR', y, blk, row, col, rN, cN)
}

SPM <- function(blk, row, col, rN = 3, cN = 1) {
    .Call('_bWGR_SPM', PACKAGE = 'bWGR', blk, row, col, rN, cN)
}

mtgsru <- function(Y, X, b, vb, ve, iG, maxit = 50L) {
    .Call('_bWGR_mtgsru', PACKAGE = 'bWGR', Y, X, b, vb, ve, iG, maxit)
}

mkr <- function(Y, K) {
    .Call('_bWGR_mkr', PACKAGE = 'bWGR', Y, K)
}

mkr2X <- function(Y, K1, K2) {
    .Call('_bWGR_mkr2X', PACKAGE = 'bWGR', Y, K1, K2)
}

